[package]
name = "dump-analyzers"
version = "0.1.0"
authors = ["Arkadiusz Guzinski <kermit@ag.de1.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = {version = "0.5.2", features = ["serde", "array-sizes-33-128"]}
#arraystring = "0.3.0"
bincode = "1.3.1"
rustc-serialize = "*"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.*"